{
    "name": "Workshop Job Card",
    "version": "18.0.1.19.0",
    "summary": "Customer Job Cards integrated with Repair Orders",
    "category": "Repair/Operations",
    "author": "dev_pmk",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "repair",
        "web",
        "report_qweb_direct_print",
        "hr",
        "workshop_product_brand",
        "workshop_customer_vehicle",
    ],
    "data": [
        "security/job_card_security.xml",
        "security/ir.model.access.csv",
        "data/job_card_sequence.xml",
        "data/inspection_result_data.xml",
        "data/inspection_template_data.xml",
        "views/product_template_views.xml",
        "views/repair_service_views.xml",
        "views/inspection_result_views.xml",
        "views/inspection_template_views.xml",
        "views/job_card_inspection_views.xml",
        "wizard/add_repair_service_wizard_views.xml",
        "wizard/remove_repair_service_wizard_views.xml",
        "wizard/inspection_check_wizard_views.xml",
        "views/job_card_views.xml",
        "views/repair_order_views.xml",
        "report/job_card_report.xml",
        "views/job_card_menu.xml",
        "data/security_cleanup.xml",
    ],
    "demo": [
        "demo/workshop_job_card_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "workshop_job_card/static/src/js/job_card_viber_share.js",
            "workshop_job_card/static/src/xml/job_card_viber_share.xml",
        ],
    },
    "installable": True,
    "application": False,
}
