from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


class WorkshopJobCardLine(models.Model):
    _name = "workshop.job.card.line"
    _description = "Workshop Job Card Product Line"
    _order = "sequence, id"

    sequence = fields.Integer(default=10)
    job_card_service_id = fields.Many2one(
        "workshop.job.card.service",
        string="Job Card Service",
        ondelete="cascade",
        index=True,
    )
    job_card_id = fields.Many2one(
        "workshop.job.card",
        string="Job Card",
        required=True,
        ondelete="cascade",
        index=True,
    )
    repair_service_id = fields.Many2one(
        related="job_card_service_id.repair_service_id",
        store=True,
        readonly=True,
    )
    repair_service = fields.Char(
        related="repair_service_id.name",
        string="Legacy Repair Service",
        store=True,
        readonly=True,
    )
    product_id = fields.Many2one(
        "product.product",
        string="Product",
        required=True,
        ondelete="restrict",
        domain=[("type", "in", ("consu", "service"))],
        context={"workshop_product_display": True},
    )
    lh_rh = fields.Selection(
        [("lh", "LH"), ("rh", "RH")],
        string="LH/RH",
    )
    brand_id = fields.Many2one(
        related="product_id.brand_id",
        string="Brand",
        store=True,
        readonly=True,
    )
    part_number = fields.Char(
        related="product_id.default_code",
        string="Part Number",
        store=True,
        readonly=True,
    )
    warranty = fields.Char()
    quantity = fields.Float(
        required=True, default=1.0, digits="Product Unit of Measure"
    )
    product_uom_id = fields.Many2one(
        "uom.uom", string="UoM", required=True, ondelete="restrict"
    )
    unit_price = fields.Monetary(required=True, default=0.0)
    amount = fields.Monetary(compute="_compute_amount", store=True, readonly=True)
    total_amount = fields.Monetary(
        string="Total Amount",
        compute="_compute_total_amount",
        store=True,
        readonly=True,
        currency_field="currency_id",
    )
    selected = fields.Boolean(string="Selected")
    generated_by_service = fields.Boolean(
        string="Generated by Repair Service",
        default=False,
        readonly=True,
        copy=False,
    )
    currency_id = fields.Many2one(
        related="job_card_id.currency_id", store=True, readonly=True
    )
    job_card_state = fields.Selection(
        related="job_card_id.state",
        store=True,
        readonly=True,
    )

    _sql_constraints = [
        (
            "workshop_job_card_line_quantity_positive",
            "check(quantity > 0)",
            "Option quantity must be greater than zero.",
        ),
        (
            "workshop_job_card_line_price_nonnegative",
            "check(unit_price >= 0)",
            "Unit price cannot be negative.",
        ),
    ]

    @api.depends("quantity", "unit_price")
    def _compute_amount(self):
        for line in self:
            line.amount = line.quantity * line.unit_price

    @api.depends(
        "amount",
        "job_card_service_id.labour_cost",
        "job_card_service_id.service_cost",
    )
    def _compute_total_amount(self):
        for line in self:
            service = line.job_card_service_id
            line.total_amount = line.amount + service.labour_cost + service.service_cost

    @api.onchange("product_id")
    def _onchange_product_id(self):
        if self.product_id:
            self.product_uom_id = self.product_id.uom_id
            self.unit_price = self.product_id.lst_price

    @api.onchange("selected", "job_card_service_id")
    def _onchange_selected(self):
        for line in self.filtered(
            lambda item: item.selected and item.job_card_service_id
        ):
            for sibling in line.job_card_service_id.option_line_ids:
                if sibling != line and sibling.selected:
                    sibling.selected = False

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            service_line = self.env["workshop.job.card.service"].browse(
                vals.get("job_card_service_id")
            )
            if service_line and not vals.get("job_card_id"):
                vals["job_card_id"] = service_line.job_card_id.id
            card = self.env["workshop.job.card"].browse(vals.get("job_card_id"))
            if (
                card
                and card.state != "draft"
                and not self.env.context.get("skip_job_card_state_check")
            ):
                raise UserError(_("Job Card product lines can only be added in Draft."))
            product = self.env["product.product"].browse(vals.get("product_id"))
            if product:
                vals.setdefault("product_uom_id", product.uom_id.id)
                vals.setdefault("unit_price", product.lst_price)
        lines = super().create(vals_list)
        legacy_selected_lines = lines.filtered(lambda line: line.selected and line.job_card_service_id)
        legacy_selected_lines._sync_selected_option()
        legacy_selected_lines._validate_single_selected_option()
        return lines

    def write(self, vals):
        vals = dict(vals)
        business_fields = {
            "sequence",
            "job_card_service_id",
            "product_id",
            "lh_rh",
            "warranty",
            "quantity",
            "product_uom_id",
            "unit_price",
            "selected",
        }.intersection(vals)
        for line in self:
            if self.env.context.get("skip_job_card_state_check"):
                continue
            if line.job_card_id.state == "sent" and business_fields - {"selected"}:
                raise UserError(_("Only option selection can be changed after sending."))
            if line.job_card_id.state not in {"draft", "sent"} and business_fields:
                raise UserError(_("Approved or closed Job Card product lines cannot be modified."))
        result = super().write(vals)
        selection_changed = (
            vals.get("selected") is True
            or ("job_card_service_id" in vals and any(self.mapped("selected")))
        )
        if selection_changed and not self.env.context.get("skip_selection_sync"):
            self.filtered(lambda line: line.selected and line.job_card_service_id)._sync_selected_option()
        self.filtered("job_card_service_id")._validate_single_selected_option()
        return result

    def unlink(self):
        if not self.env.context.get("skip_job_card_state_check") and any(
            line.job_card_id.state != "draft" for line in self
        ):
            raise UserError(_("Job Card product lines can only be deleted in Draft."))
        return super().unlink()

    def _sync_selected_option(self):
        """Keep the current option and clear selected siblings in its service."""
        for line in self:
            if not line.selected:
                continue
            competitors = self.search(
                [
                    ("job_card_service_id", "=", line.job_card_service_id.id),
                    ("selected", "=", True),
                    ("id", "!=", line.id),
                ]
            )
            if competitors:
                competitors.with_context(skip_selection_sync=True).write(
                    {"selected": False}
                )

    def _validate_single_selected_option(self):
        """Fallback protection for imports, RPC calls, and internal writes."""
        service_lines = self.mapped("job_card_service_id")
        for service_line in service_lines:
            selected_count = self.search_count(
                [
                    ("job_card_service_id", "=", service_line.id),
                    ("selected", "=", True),
                ],
                limit=2,
            )
            if selected_count > 1:
                raise ValidationError(
                    _(
                        "Only one Product Option may be selected for each "
                        "Job Card Repair Service."
                    )
                )

    @api.constrains("quantity", "unit_price", "product_id", "product_uom_id")
    def _check_line_values(self):
        for line in self:
            if line.quantity <= 0:
                raise ValidationError(_("Option quantity must be greater than zero."))
            if line.unit_price < 0:
                raise ValidationError(_("Unit price cannot be negative."))
            if (
                line.product_id
                and line.product_uom_id
                and line.product_uom_id.category_id != line.product_id.uom_id.category_id
            ):
                raise ValidationError(
                    _("The option UoM must use the product's UoM category.")
                )

    @api.constrains("job_card_id", "job_card_service_id")
    def _check_job_card_service(self):
        for line in self:
            if (
                line.job_card_service_id
                and line.job_card_service_id.job_card_id != line.job_card_id
            ):
                raise ValidationError(
                    _("The option line and Repair Service must belong to the same Job Card.")
                )

    @api.constrains("job_card_service_id", "product_id")
    def _check_duplicate_product_option(self):
        for line in self:
            if line.job_card_service_id and line.product_id and self.search_count(
                [
                    ("job_card_service_id", "=", line.job_card_service_id.id),
                    ("product_id", "=", line.product_id.id),
                    ("id", "!=", line.id),
                ],
                limit=1,
            ):
                raise ValidationError(
                    _(
                        "The same Product Option cannot be added more than once "
                        "to one Repair Service."
                    )
                )
